# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint.xdc

# IP: ip/inst_mem/inst_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_mem || ORIG_REF_NAME==inst_mem} -quiet] -quiet

# IP: ip/uart_bmpg_0_2/uart_bmpg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_bmpg_0 || ORIG_REF_NAME==uart_bmpg_0} -quiet] -quiet
